name: simplest-load-balancer
adopt-info: version
summary: Sessionless UDP Load Balancer
description: |
  SLB is a sessionless load balancer for UDP traffic, and solves
  problems inherent with using traditional (feature rich)
  load balancers for such traffic.
source-code: https://github.com/mlhpdx/SimplestLoadBalancer
website: https://github.com/mlhpdx/SimplestLoadBalancer
license: MIT
environment:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

grade: stable # or 'devel' for development versions
confinement: strict # or 'devmode' for development

base: core22 # Ubuntu 22.04 LTS base

apps:
  simplest-load-balancer:
    command: bin/SimplestLoadBalancer
    plugs:
      - network
      - network-bind
      - home

parts:
  version:
    plugin: nil
    override-pull: |
      set -ex
      craftctl set version="$(cd $SNAPCRAFT_PROJECT_DIR && git describe --tags)"

  simplest-load-balancer:
    plugin: dump
    source: .
    build-packages:
      - unzip
      - wget
    override-build: |
      craftctl default
      wget -O release.zip $URL_X64
      unzip release.zip
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp $CRAFT_PART_SRC/publish/SimplestLoadBalancer $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/SimplestLoadBalancer
