name: Release MSI

on: 
  workflow_dispatch:
  release: 
    types:
      - created

jobs:
  publish:
    runs-on: windows-latest    
    strategy:
      matrix:
        rid: [win-x64]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Get the Tagged Version
      id: get_version
      shell: bash
      run: |
        echo "VERSION=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
        echo "RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)" >> "$GITHUB_OUTPUT"
    - name: Publish for OS
      run: dotnet publish SimplestLoadBalancer.csproj -o ./slb-${{ matrix.rid }} -c Release -r ${{ matrix.rid }} /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:Version=${{ steps.get_version.outputs.VERSION }} --self-contained
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Install WiX
      run: |
        dotnet tool install --global wix
        wix extension add WixToolset.UI.wixext
        wix extension add WixToolset.Firewall.wixext
    - name: Build WiX on Windows
      run: wix build package.wxs -define PublishDir=./slb-${{ matrix.rid }} -o SimplestLoadBalancer-${{ steps.get_version.outputs.VERSION }}-${{ matrix.rid }}.msi -ext WixToolset.UI.wixext -ext WixToolset.Firewall.wixext
    - name: Upload MSI to Releaase
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        FILE: SimplestLoadBalancer-${{ steps.get_version.outputs.VERSION }}-${{ matrix.rid }}.msi
        URL: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_version.outputs.RELEASE_ID }}/assets?name=SimplestLoadBalancer-${{ steps.get_version.outputs.VERSION }}-${{ matrix.rid }}.msi
      run: |
        echo $VERSION
        echo $URL
        AUTH="Authorization: token $GITHUB_TOKEN"
        echo $AUTH
        curl -sSL -XPOST -H "$AUTH" --upload-file "$FILE" --header "Content-Type:application/octet-stream" --write-out "%{http_code}" --output $(mktemp) "$URL"
