name: Release
on: 
  release: 
    types:
      - created
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            os: ubuntu-latest
          - rid: linux-arm
            os: ubuntu-latest
            apt_packages: lld gcc-arm-linux-gnueabihf
            publish_args: /p:CppCompilerAndLinker=clang /p:LinkerFlavor=lld /p:SysRoot=/usr/arm-linux-gnueabihf
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Get the Tagged Version
      id: get_version
      run: | 
        echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT
    - name: Install cross-compilation toolchain
      if: matrix.apt_packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.apt_packages }}
    - name: Publish for OS
      run: dotnet publish SimplestLoadBalancer.csproj -o ./slb-${{ matrix.rid }} -c Release -r ${{ matrix.rid }} /p:Version=${{ github.ref_name }} ${{ matrix.publish_args }}
    - name: Zip it Up
      run: zip -r -j SimplestLoadBalancer-${{ github.ref_name }}-${{ matrix.rid }}.zip ./slb-${{ matrix.rid }}
    - name: Upload ZIP to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref_name }}
        FILE: SimplestLoadBalancer-${{ github.ref_name }}-${{ matrix.rid }}.zip
        URL: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_version.outputs.RELEASE_ID }}/assets?name=SimplestLoadBalancer-${{ github.ref_name }}-${{ matrix.rid }}.zip
      run: |
        echo $VERSION
        echo $URL
        AUTH="Authorization: token $GITHUB_TOKEN"
        echo $AUTH
        curl -sSL -XPOST -H "$AUTH" --upload-file "$FILE" --header "Content-Type:application/octet-stream" --write-out "%{http_code}" --output $(mktemp) "$URL"
  snap:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: snapcore/action-build@v1
        id: build
        env: 
          VERSION: ${{ github.ref_name }}
          URL_X64: https://github.com/mlhpdx/SimplestLoadBalancer/releases/download/${{ github.ref_name }}/SimplestLoadBalancer-${{ github.ref_name }}-linux-x64.zip
          URL_ARM64: https://github.com/mlhpdx/SimplestLoadBalancer/releases/download/${{ github.ref_name }}/SimplestLoadBalancer-${{ github.ref_name }}-linux-arm.zip
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable